name: torch_env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - pip
  - python
  - tqdm
  - wheel
  - pip:
      - matplotlib
      - numpy
      - pillow
      - scikit-image
      - scipy
      # 请在https://pytorch.org/get-started/locally/中找到需要的pytorch版本
      # - torch
      - jsonref
      - toolz
      - tqdm
      - torchsummary
      - opencv-python
      - torchmetrics
      - pandas
      - torchinfo
